package amyc
package codegen

import analyzer._
import amyc.ast.Identifier
import amyc.ast.SymbolicTreeModule.{Call => AmyCall, Div => AmyDiv, And => AmyAnd, Or => AmyOr, _}
import amyc.utils.{Context, Pipeline}
import wasm._
import Instructions._
import Utils._

// Generates WebAssembly code for an Amy program
object CodeGen extends Pipeline[(Program, SymbolTable), Module] {
  def run(ctx: Context)(v: (Program, SymbolTable)): Module = {
    val (program, table) = v

    // Generate code for an Amy module
    def cgModule(moduleDef: ModuleDef): List[Function] = {
      val ModuleDef(name, defs, optExpr) = moduleDef
      // Generate code for all functions
      defs.collect { case fd: FunDef if !builtInFunctions(fullName(name, fd.name)) =>
        cgFunction(fd, name, false)
      } ++
      // Generate code for the "main" function, which contains the module expression
      optExpr.toList.map { expr =>
        val mainFd = FunDef(Identifier.fresh("main"), Nil, TypeTree(IntType), expr)
        cgFunction(mainFd, name, true)
      }
    }

    // Generate code for a function in module 'owner'
    def cgFunction(fd: FunDef, owner: Identifier, isMain: Boolean): Function = {
      // Note: We create the wasm function name from a combination of
      // module and function name, since we put everything in the same wasm module.
      val name = fullName(owner, fd.name)
      Function(name, fd.params.size, isMain){ lh =>
        val locals = fd.paramNames.zipWithIndex.toMap
        val body = cgExpr(fd.body)(using locals, lh)
        val comment = Comment(fd.toString)
        if (isMain) {
          body <:> Drop // Main functions do not return a value,
                        // so we need to drop the value generated by their body
        } else {
          comment <:> body
        }
      }
    }


    // Generate code for an expression expr.
    // Additional arguments are a mapping from identifiers (parameters and variables) to
    // their index in the wasm local variables, and a LocalsHandler which will generate
    // fresh local slots as required.
    def cgExpr(expr: Expr)(implicit locals: Map[Identifier, Int], lh: LocalsHandler): Code = {
      def cgArgs(args: List[Expr]): Code =
        args.foldLeft(Code(Nil): Code)((acc, e) => acc <:> cgExpr(e))

      def matchAndBind(pat: Pattern, valueLocal: Int): (Code, Map[Identifier, Int]) = pat match {
        case WildcardPattern() =>
          (Const(1), Map.empty)

        case IdPattern(id) =>
          val local = lh.getFreshLocal()
          (GetLocal(valueLocal) <:> SetLocal(local) <:> Const(1), Map(id -> local))

        case LiteralPattern(lit) =>
          (GetLocal(valueLocal) <:> cgExpr(lit) <:> Eq, Map.empty)

        case CaseClassPattern(constr, args) =>
          val sig = table.getConstructor(constr).get
          val tagCheck = GetLocal(valueLocal) <:> Load <:> Const(sig.index) <:> Eq

          if (args.isEmpty) {
            (tagCheck, Map.empty)
          } else {
            val (fieldsCode, allBindings) = 
              args.zipWithIndex.foldLeft((Const(1): Code, Map.empty[Identifier, Int])) {
                case ((code, bindings), (pat, index)) =>
                  val fieldLocal = lh.getFreshLocal()
                  val loadField = GetLocal(valueLocal) <:> adtField(index) <:> Load <:> SetLocal(fieldLocal)
                  val (fieldCheck, fieldBindings) = matchAndBind(pat, fieldLocal)

                  (code <:> loadField <:> fieldCheck <:> And, bindings ++ fieldBindings)
              }

            (tagCheck <:> If_i32 <:> fieldsCode <:> Else <:> Const(0) <:> End, allBindings)
          }
      }

      // i have no idea if this works - but it can be very useful for the match expression, so i hope it does
      def cgCases(cases: List[MatchCase], scrutLocal: Int): Code = cases match {
        case Nil => Unreachable
        case MatchCase(pat, rhs) :: rest =>
          val (check, bindings) = matchAndBind(pat, scrutLocal)
          check <:> If_i32 <:> cgExpr(rhs)(using locals ++ bindings, lh) <:> Else <:> cgCases(rest, scrutLocal) <:> End
      }

      expr match {
        case IntLiteral(i) =>
          Comment(expr.toString) <:> Const(i)

        case BooleanLiteral(b) =>
          Comment(expr.toString) <:> Const(if (b == true) 1 else 0)

        case StringLiteral(s) =>
          Comment(expr.toString) <:> mkString(s) //Creates a known string constant s in memory

        case UnitLiteral() =>
          Comment(expr.toString) <:> Const(0)

        case Variable(name) =>
          Comment(expr.toString) <:> GetLocal(locals(name))

        case Plus(lhs, rhs) =>
          cgExpr(lhs) <:> cgExpr(rhs) <:> Add

        case Minus(lhs, rhs) =>
          cgExpr(lhs) <:> cgExpr(rhs) <:> Sub

        case Times(lhs, rhs) =>
          cgExpr(lhs) <:> cgExpr(rhs) <:> Mul

        case AmyDiv(lhs, rhs) =>
          cgExpr(lhs) <:> cgExpr(rhs) <:> Div // no need to check div 0 

        case Mod(lhs, rhs) =>
          cgExpr(lhs) <:> cgExpr(rhs) <:> Rem // rem is for modulo

        case LessThan(lhs, rhs) =>
          cgExpr(lhs) <:> cgExpr(rhs) <:> Lt_s

        case LessEquals(lhs, rhs) =>
          cgExpr(lhs) <:> cgExpr(rhs) <:> Le_s

        case AmyAnd(lhs, rhs) =>
          cgExpr(lhs) <:> If_i32 <:> cgExpr(rhs) <:> Else <:> Const(0) <:> End

        case AmyOr(lhs, rhs) =>
          cgExpr(lhs) <:> If_i32 <:> Const(1) <:> Else <:> cgExpr(rhs) <:> End

        case Equals(lhs, rhs) =>
          cgExpr(lhs) <:> cgExpr(rhs) <:> Eq

        case Concat(lhs, rhs) =>
          Comment(expr.toString) <:> cgExpr(lhs) <:> cgExpr(rhs) <:> Call("String_concat")

        case Not(e) =>
          cgExpr(e) <:> Eqz // if expression is true then return false if false return true

        case Neg(e) =>
          Const(0) <:> cgExpr(e) <:> Sub // do 0 - value to get it's negation

        case AmyCall(qname, args) =>
          table.getConstructor(qname) match {
            case Some(sig) =>
              val ptrLocal = lh.getFreshLocal()
              val storeFields = args.zipWithIndex.foldLeft(Code(Nil): Code) {
                case (codeAcc, (arg, idx)) =>
                  codeAcc <:> GetLocal(ptrLocal) <:> adtField(idx) <:> cgExpr(arg) <:> Store
              }
              Comment(expr.toString) <:>
                GetGlobal(memoryBoundary) <:> SetLocal(ptrLocal) <:>
                GetLocal(ptrLocal) <:> Const(4 + 4 * args.length) <:> Add <:> SetGlobal(memoryBoundary) <:>
                GetLocal(ptrLocal) <:> Const(sig.index) <:> Store <:>
                storeFields <:>
                GetLocal(ptrLocal)
            case None =>
              val fnName = table.getFunction(qname).map(sig => fullName(sig.owner, qname)).getOrElse(qname.fullName)
              Comment(expr.toString) <:> cgArgs(args) <:> Call(fnName)
          }

        case Sequence(e1, e2) =>
          Comment(expr.toString) <:> cgExpr(e1) <:> Drop <:> cgExpr(e2)

        case Let(df, value, body) =>
          val local = lh.getFreshLocal()
          Comment(expr.toString) <:> cgExpr(value) <:> SetLocal(local) <:> cgExpr(body)(using locals + (df.name -> local), lh)

        case Ite(cond, thenn, elze) =>
          Comment(expr.toString) <:> cgExpr(cond) <:> If_i32 <:> cgExpr(thenn) <:> Else <:> cgExpr(elze) <:> End

        case Match(scrut, cases) =>
          val scrutLocal = lh.getFreshLocal()
          Comment(expr.toString) <:> cgExpr(scrut) <:> SetLocal(scrutLocal) <:> cgCases(cases, scrutLocal)

        case Error(msg) =>
          Comment(expr.toString) <:> cgExpr(msg) <:> Unreachable
        }
    }

    Module(
      program.modules.last.name.name,
      defaultImports,
      globalsNo,
      wasmFunctions ++ (program.modules flatMap cgModule)
    )
  }
}
